# Top-level configuration
name = "raisetheflag"
main = "./index.js"
compatibility_date = "2024-08-27"

workers_dev = false
route = { pattern = "tunnel.mycyberadvantage.com.au/secure/{COUNTRY}", zone_name = "example.org" }

r2_buckets  = [
  { binding = "<flags>", bucket_name = "<country-flags>"},
]
