name = "my-secure-worker"
type = "javascript"
account_id = "your_account_id"
workers_dev = true
compatibility_date = "2024-08-21"

[env.production]
# Bind the R2 bucket
[[r2_buckets]]
binding = "MY_R2_BUCKET"
bucket_name = "your_bucket_name"
preview_bucket_name = "your_bucket_name"
