# Top-level configuration
name = "raisetheflag"
main = "./index.js"
compatibility_date = "2024-08-27"

workers_dev = false
routes = [ 
  { pattern = "tunnel.mycyberadvantage.com.au/secure", zone_name = "mycyberadvantage.com.au" },
  { pattern = "tunnel.mycyberadvantage.com.au/secure/{COUNTRY}", zone_name = "mycyberadvantage.com.au" }
]

r2_buckets  = [
  { binding = "FLAGS", bucket_name = "flag-images" },
]
